import React from 'react';
import { ShieldAlert, X } from 'lucide-react';

interface DisclaimerModalProps {
  onClose: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ onClose }) => {
  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white rounded-3xl shadow-2xl max-w-xl w-full border border-slate-200 overflow-hidden my-8 animate-in zoom-in-95 duration-200">
        
        <div className="bg-[#0F2D5C] text-white p-5 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-[#F4B400]" />
            <h3 className="font-bold text-lg">Engineering & Legal Disclaimer</h3>
          </div>
          <button onClick={onClose} className="p-1 rounded-lg text-slate-300 hover:text-white">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 text-slate-700 text-xs sm:text-sm leading-relaxed space-y-3 max-h-96 overflow-y-auto">
          <p>
            <strong>1. Educational & Estimational Purpose:</strong> All calculations, outputs, mix ratio proportions, steel rebar weights, and budget allocations provided by BuildMetric are intended solely for estimation and planning purposes.
          </p>
          <p>
            <strong>2. Variance & Site Conditions:</strong> Real-world material requirements can vary due to ground compaction, soil bearing capacity, moisture absorption in sand, contractor workmanship, site spillage, and local building code modifications.
          </p>
          <p>
            <strong>3. Professional Consultation Required:</strong> Users are advised to verify all critical structural calculations with a licensed professional civil or structural engineer prior to placing order requisitions or commencing structural casting.
          </p>
          <p>
            <strong>4. Limitation of Liability:</strong> BuildMetric accepts no liability or responsibility for loss or damages resulting from reliance upon the calculations generated by this platform.
          </p>
        </div>

        <div className="bg-slate-100 px-6 py-4 border-t border-slate-200 flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-xl bg-[#0F2D5C] text-[#F4B400] font-bold text-xs"
          >
            I Understand & Accept
          </button>
        </div>

      </div>
    </div>
  );
};
