import React from 'react';
import { SEO } from './SEO';
import { FileText } from 'lucide-react';

export const TermsPage: React.FC = () => {
  return (
    <div className="py-12 bg-slate-50 min-h-screen">
      <SEO 
        title="Terms of Service | BuildMetric Construction Tools"
        description="Terms of Service and engineering usage guidelines for BuildMetric calculators."
        canonicalUrl="https://buildmetric-app.vercel.app/terms"
      />
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
        <div className="bg-white rounded-3xl border border-slate-200 p-8 sm:p-12 shadow-sm space-y-6">
          
          <div className="flex items-center gap-3 border-b border-slate-100 pb-6">
            <div className="w-12 h-12 rounded-2xl bg-blue-50 text-[#0F2D5C] flex items-center justify-center">
              <FileText className="w-6 h-6 text-[#F4B400]" />
            </div>
            <div>
              <h1 className="text-3xl font-black text-slate-900">Terms of Service</h1>
              <p className="text-xs font-semibold text-slate-400">Last updated: August 2026</p>
            </div>
          </div>

          <div className="space-y-6 text-slate-600 text-sm leading-relaxed">
            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-900">1. Terms of Use</h2>
              <p>
                By accessing BuildMetric, you agree to utilize these construction estimation and civil engineering tools for informational, preliminary budgeting, and planning purposes.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-900">2. Engineering Disclaimer</h2>
              <p>
                Calculations generated by BuildMetric rely on standard nominal material ratios (IS 456, ACI 318, BS 8110) and standard unit densities. Because real-world site conditions, material moisture content, aggregate compaction, and contractor execution vary, estimates provided by this site should be verified by a licensed civil engineer or project manager prior to procurement.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-slate-900">3. Intellectual Property</h2>
              <p>
                All interface designs, branding, logos, and custom calculation scripts on BuildMetric are protected under international copyright law.
              </p>
            </section>
          </div>

        </div>
      </div>
    </div>
  );
};
